export const CLEANING_CATALOG: Record<string, string[]> = {
  'Kitchen': [
    'Wipe all countertops and backsplash',
    'Clean stovetop and burners',
    'Clean oven interior',
    'Clean microwave inside and out',
    'Wipe exterior of refrigerator',
    'Clean inside refrigerator, remove old items',
    'Run dishwasher or hand-wash dishes',
    'Empty and reline trash can',
    'Wipe cabinet fronts',
    'Sweep and mop floor',
    'Restock dish soap, sponge, paper towels',
  ],
  'Bathrooms': [
    'Scrub toilet bowl, seat, and base',
    'Clean sink and faucet',
    'Wipe mirror',
    'Scrub shower/tub and glass doors',
    'Sweep and mop floor',
    'Empty trash and reline',
    'Restock toilet paper, hand soap, shampoo/conditioner',
    'Replace bath mat if needed',
    'Wipe exhaust fan cover',
  ],
  'Bedrooms': [
    'Strip bed linens and pillowcases',
    'Make bed with fresh linens',
    'Dust furniture surfaces',
    'Wipe nightstands and lamps',
    'Vacuum floor and rugs',
    'Check under bed',
    'Empty trash',
    'Check closet and dresser drawers for left items',
    'Restock extra blankets/pillows if needed',
  ],
  'Living Areas': [
    'Dust all furniture',
    'Wipe TV screen and remotes',
    'Fluff and rearrange cushions',
    'Vacuum upholstered furniture',
    'Sweep and vacuum floors',
    'Mop hard floors',
    'Empty all trash',
    'Wipe light switches and door handles',
    'Check windows for smudges',
  ],
  'Laundry': [
    'Run all used towels and linens through washer/dryer',
    'Fold and return towels to bathrooms',
    'Wipe washer and dryer exteriors',
    'Clean lint trap',
  ],
  'Outdoor / Entry': [
    'Sweep front entry and porch',
    'Wipe outdoor furniture',
    'Remove any trash or debris from yard',
    'Check and clear grill grates',
    'Wipe door handles and keypad',
  ],
  'Final Checks': [
    'Check all windows are closed and locked',
    'Turn off all lights',
    'Set thermostat to default temperature',
    'Lock all doors',
    'Take photos of each room',
    'Report any damage or missing items',
  ],
}
