#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Regenerates supabase/schema_reference.sql from the live database.
#
# This file is AUTO-GENERATED. Do not edit it manually.
# Run this script before any audit or schema review to ensure accuracy.
#
# Usage:
#   bash scripts/generate-schema-reference.sh
#
# Requirements:
#   - Supabase CLI installed (npm i -g supabase or brew install supabase)
#   - Logged in: supabase login
#   - Linked project: supabase link --project-ref vpmznjktllhmmbfnxuvk
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

PROJECT_REF="vpmznjktllhmmbfnxuvk"
OUTPUT_FILE="supabase/schema_reference.sql"

echo "Generating schema reference from project $PROJECT_REF..."

# Write auto-generated header
cat > "$OUTPUT_FILE" << HEADER
-- ─────────────────────────────────────────────────────────────────────────────
-- AUTO-GENERATED — do not edit this file manually.
-- Run: bash scripts/generate-schema-reference.sh
--
-- Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
-- Project:   $PROJECT_REF
-- ─────────────────────────────────────────────────────────────────────────────

HEADER

# Append the full schema dump (schema only, no data, no owner statements)
supabase db dump \
  --project-ref "$PROJECT_REF" \
  --schema public \
  >> "$OUTPUT_FILE"

echo "Done — schema reference written to $OUTPUT_FILE"
echo "Lines: $(wc -l < "$OUTPUT_FILE")"
