-- ============================================================================
-- approveQuoteRequest becomes one transaction.
--
-- The server action did four writes in sequence with no way back from a
-- failure partway through:
--
--   1. claim the winning quote          (status -> 'approved')
--   2. decline every sibling quote      (pending/submitted -> 'declined')
--   3. assign the vendor to the work order (+ portal_enabled, completion token)
--   4. log the status change
--
-- If step 3 failed — an RLS denial, a constraint, a dropped connection — the
-- action returned a generic error and left the work order in a state nobody
-- can recover from the UI: the winning quote already says 'approved', every
-- competing quote already says 'declined', and the work order is still
-- UNASSIGNED with no live RFQ left to approve. The PM's only remaining option
-- is to re-request quotes from scratch, and nothing in the interface explains
-- why the approved quote produced no vendor.
--
-- Step 2's result was discarded outright, and it was not org-scoped: it
-- matched on work_order_id alone, relying entirely on RLS for tenant
-- isolation rather than stating it.
--
-- All four writes now happen inside one function body, so either the vendor is
-- assigned and the quotes are settled, or nothing changed at all. Both parent
-- rows are locked FOR UPDATE before the first write, so the two "cannot
-- proceed" cases are detected BEFORE anything is modified and can be returned
-- as ordinary outcomes rather than needing a rollback.
--
-- status_from on the log row is now the work order's REAL prior status. The
-- action hardcoded 'pending', which was simply wrong whenever the work order
-- sat in 'quote_requested' — which is the normal state for a work order that
-- has quotes to approve.
--
-- SECURITY DEFINER, so RLS does not apply inside the body: the explicit
-- p_org_id predicate on every statement IS the tenant boundary. The caller
-- passes membership.org_id from requireOrgRole(['admin','manager']), never a
-- client-supplied value. The completion token is generated by the caller
-- (crypto.randomUUID) and passed in, so token generation stays in one place.
--
-- Vendor compliance is deliberately NOT checked here: it stays in the action,
-- ahead of this call, because a hard-blocked vendor must be refused before any
-- claim happens at all.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.approve_quote_request(
  p_quote_request_id  uuid,
  p_org_id            uuid,
  p_completion_token  text,
  p_token_expires_at  timestamptz
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_work_order_id uuid;
  v_vendor_id     uuid;
  v_quoted        numeric;
  v_qr_status     quote_request_status;
  v_wo_status     wo_status;
  v_declined      integer := 0;
BEGIN
  SELECT work_order_id, vendor_id, quoted_amount, status
    INTO v_work_order_id, v_vendor_id, v_quoted, v_qr_status
    FROM public.quote_requests
   WHERE id     = p_quote_request_id
     AND org_id = p_org_id
     FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'quote_not_found');
  END IF;

  IF v_qr_status <> 'submitted' THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_submitted');
  END IF;

  -- Lock the work order BEFORE claiming anything, so a work order that cannot
  -- be assigned is refused while the quotes are still untouched. This is what
  -- makes the "approved quote, no vendor, no live RFQ" dead end impossible.
  SELECT status INTO v_wo_status
    FROM public.work_orders
   WHERE id     = v_work_order_id
     AND org_id = p_org_id
     FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'work_order_not_found');
  END IF;

  UPDATE public.quote_requests
     SET status = 'approved'
   WHERE id = p_quote_request_id;

  UPDATE public.quote_requests
     SET status = 'declined'
   WHERE work_order_id = v_work_order_id
     AND org_id        = p_org_id
     AND id           <> p_quote_request_id
     AND status IN ('pending', 'submitted');
  GET DIAGNOSTICS v_declined = ROW_COUNT;

  UPDATE public.work_orders
     SET vendor_id                  = v_vendor_id,
         status                     = 'assigned',
         estimated_cost             = COALESCE(v_quoted, estimated_cost),
         portal_enabled             = true,
         completion_token           = p_completion_token,
         completion_token_expires_at = p_token_expires_at
   WHERE id     = v_work_order_id
     AND org_id = p_org_id;

  INSERT INTO public.work_order_updates (
    work_order_id, org_id, updated_via_vendor_portal,
    status_from, status_to, notes
  ) VALUES (
    v_work_order_id, p_org_id, false,
    v_wo_status, 'assigned',
    'Quote approved — $' || COALESCE(to_char(v_quoted, 'FM999999990.00'), '?')
      || '. Vendor assigned and notified.'
  );

  RETURN jsonb_build_object(
    'ok',            true,
    'work_order_id', v_work_order_id,
    'vendor_id',     v_vendor_id,
    'quoted_amount', v_quoted,
    'declined',      v_declined
  );
END;
$$;

REVOKE EXECUTE ON FUNCTION public.approve_quote_request(uuid, uuid, text, timestamptz) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.approve_quote_request(uuid, uuid, text, timestamptz) TO authenticated, service_role;

NOTIFY pgrst, 'reload schema';
