// lib/integrations/providers/lodgify-api.ts
// ============================================================================
// Authenticated Lodgify Public API v2 client: properties, bookings, webhooks.
//
// Separate from lodgify.ts (the provider adapter) for the same reason
// hostex-api.ts is separate from hostex.ts — the adapter is about holding a
// credential, this is about spending one.
//
// HOW LODGIFY DIFFERS FROM THE PROVIDERS ALREADY HERE:
//
//   1. AUTH IS A RAW ACCOUNT KEY IN A HEADER — `X-ApiKey`, generated by the
//      PM in Lodgify under Settings -> Public API. No OAuth, no refresh, and
//      NO REVOCATION ENDPOINT: disconnecting deletes our copy, it does not
//      invalidate the key. That is a weaker posture than OwnerRez/Hostex and
//      is stated in the adapter's disconnect path rather than papered over.
//   2. HTTP STATUS IS MEANINGFUL, unlike Hostex's always-200 envelope. So the
//      classification below is a plain status ladder.
//   3. THE RESPONSE SHAPES ARE UNVERIFIED. See lodgify.types.ts's header. The
//      practical consequence lives in lodgifyExtractItems: a list response
//      that matches neither documented shape REPORTS the keys it actually saw
//      and throws, rather than returning [] — because [] from a fetch is the
//      input that makes every reconcile-by-absence pass delete everything
//      (the `absence-reconciliation` guardrail, and the day one org's whole
//      crew roster was deactivated at the same microsecond).
//
// Pagination is `page`/`size`. Lodgify's documented maximum page size is 50.
// ============================================================================

import 'server-only'

import { NonRetriableError } from 'inngest'

import {
  ProviderAuthError,
  ProviderEntityGoneError,
  ProviderRequestError,
  RateLimitError,
} from '@/lib/integrations/types'
import { checkLimit, lodgifyApiLimiter, outboundBackoffSeconds } from '@/lib/rate-limit'
import { evaluateBreaker, recordFailure, recordSuccess, CircuitOpenError } from '@/lib/integrations/circuit-breaker'
import { rateLimitRetry } from '@/lib/inngest/retry-after'
import { PMS_API_TIMEOUT_MS } from '@/lib/http/timeout'
import { fetchWithRetry } from '@/lib/http/retry'
import { reportError } from '@/lib/observability/report-error'
import { lodgifyProvider } from '@/lib/integrations/providers/lodgify'
import type {
  LodgifyBooking,
  LodgifyBookingEvent,
  LodgifyProperty,
  LodgifyWebhookSubscription,
} from '@/lib/integrations/providers/lodgify.types'

const LODGIFY_API_BASE = 'https://api.lodgify.com/v2'

/** Lodgify's documented maximum for the `size` query param. */
const PAGE_SIZE = 50

/**
 * Hard ceiling on pages per collection fetch. 200 pages x 50 = 10,000 rows,
 * far beyond any self-serve portfolio. Exists so a server that ignores `page`
 * cannot spin this loop forever inside an Inngest step — the same guard, and
 * the same reason, as hostex-api.ts's MAX_PAGES.
 */
const MAX_PAGES = 200

export const LODGIFY_PROVIDER_LABEL = 'Lodgify'

/**
 * Statuses no retry can clear. Everything absent from this set — 5xx, and any
 * status Lodgify invents later — stays retryable, so an unknown failure errs
 * toward trying again rather than toward silently giving up.
 *
 * 429 is deliberately NOT here: it is handled before this set is consulted.
 */
const TERMINAL_STATUSES = new Set([400, 401, 403, 404, 405, 409, 422])

/**
 * Jitter a provider-supplied Retry-After by ±25%.
 *
 * One FieldStay deploy runs every org's syncs, so a platform-wide cron that
 * throttles throttles many connections at once, and an unjittered backoff
 * marches all of them into the next window together. Same convention, and the
 * same ±25% spread, as hostex-api.ts.
 */
function withRetryJitter(seconds: number): number {
  // eslint-disable-next-line no-restricted-properties -- backoff jitter, not an id or a token; crypto randomness would be pointless here
  const factor = 0.75 + Math.random() * 0.5 // NOSONAR -- timing jitter only, not security-sensitive (see eslint-disable justification above)
  return Math.max(1, Math.ceil(seconds * factor))
}

/** Lodgify's Retry-After, or a conservative default when it sends none. */
function retryAfterSecondsFrom(res: Response): number {
  const parsed = Number.parseInt(res.headers.get('Retry-After') ?? '', 10)
  return withRetryJitter(Number.isFinite(parsed) && parsed > 0 ? parsed : 60)
}

/**
 * The head of an error body, for the thrown message.
 *
 * Truncated hard: this string reaches integration_connections.metadata via
 * syncErrorDetail(), which staff read. Lodgify echoes request parameters in
 * some error bodies, and the API key travels in a HEADER rather than a
 * parameter, so it cannot appear here — but the truncation is what keeps that
 * true of any field Lodgify adds later.
 */
async function errorDetail(res: Response): Promise<string> {
  try {
    return (await res.text()).slice(0, 200)
  } catch {
    return ''
  }
}

/**
 * Turn a non-OK response into the right typed error.
 *
 * Terminal failures are wrapped in NonRetriableError with the typed error as
 * `cause`, so Inngest stops at the first attempt while a caller can still
 * branch on what actually happened — the same shape hostexFetch uses.
 */
async function throwForStatus(res: Response, path: string, entityId?: string): Promise<never> {
  const detail = await errorDetail(res)

  // Wrapped in rateLimitRetry so Inngest waits the interval LODGIFY asked for
  // rather than its own backoff curve. Deliberately NOT a breaker failure:
  // a provider working correctly and telling us to slow down is not the
  // provider failing — the same exemption hostexFetch and krogerFetch make.
  if (res.status === 429) throw rateLimitRetry(new RateLimitError(retryAfterSecondsFrom(res)))

  if (res.status === 401 || res.status === 403) {
    const failure = new ProviderAuthError(LODGIFY_PROVIDER_LABEL, res.status, path, detail)
    throw new NonRetriableError(failure.message, { cause: failure })
  }

  if (res.status === 404 && entityId) {
    const failure = new ProviderEntityGoneError(LODGIFY_PROVIDER_LABEL, path, entityId, detail)
    throw new NonRetriableError(failure.message, { cause: failure })
  }

  if (TERMINAL_STATUSES.has(res.status)) {
    const failure = new ProviderRequestError(LODGIFY_PROVIDER_LABEL, res.status, path, detail)
    throw new NonRetriableError(failure.message, { cause: failure })
  }

  // Everything left is 5xx-shaped: Lodgify FAILING, rather than us being
  // wrong (the terminal statuses above) or being throttled (the 429 above).
  // That is exactly what the breaker should count.
  await recordFailure('lodgify')

  const suffix = detail ? ` — ${detail}` : ''
  throw new Error(`Lodgify ${path} failed: HTTP ${res.status}${suffix}`)
}

/**
 * True when `err` is Lodgify refusing the CREDENTIAL rather than the request.
 *
 * Unwraps `cause` as well as testing `err` directly, because an auth failure
 * is terminal and therefore always reaches a caller wrapped in a
 * NonRetriableError, never bare — a check that only tested `err` would match
 * exactly none of the cases it exists for (hostex-api.ts learned this one).
 */
export function isLodgifyAuthFailure(err: unknown): boolean {
  const inner = err instanceof ProviderAuthError ? err : (err as { cause?: unknown })?.cause
  return inner instanceof ProviderAuthError
}

interface LodgifyRequestInit {
  method?: 'GET' | 'POST' | 'PUT' | 'DELETE'
  body?:   unknown
  /** Named in the path — turns a 404 into ProviderEntityGoneError. */
  entityId?: string
}

/**
 * Spend one token of this connection's outbound budget, or throw.
 *
 * Fails CLOSED: this budget exists to throw before Lodgify throttles us, and
 * Lodgify's real ceiling is unverified (see lodgifyApiLimiter's comment). If
 * the budget cannot be consulted we must not guess our way through it —
 * Inngest's step retry handles the backoff.
 *
 * Extracted from lodgifyFetch for the same cognitive-complexity reason as
 * hostex-api.ts's enforceHostexRateLimit.
 */
async function enforceLodgifyRateLimit(userId: string): Promise<void> {
  const budget = await checkLimit(lodgifyApiLimiter, `lodgify-api:${userId}`, {
    onError: 'deny',
    site:    'lib.integrations.lodgify-api.lodgifyFetch',
  })

  if (budget.allowed) return

  // outboundBackoffSeconds rather than a bare `reset` subtraction: when the
  // limiter itself ERRORS, checkLimit sets reset to Date.now(), so that
  // subtraction floors to 1s and we would retry a provider immediately during
  // the very outage that made the budget unreadable.
  //
  // jitter:false because withRetryJitter is this module's own spread and
  // applying both would compound them.
  throw rateLimitRetry(new RateLimitError(withRetryJitter(outboundBackoffSeconds(budget, { jitter: false }))))
}

/**
 * The raw HTTP call, with the circuit breaker's failure bookkeeping around it.
 *
 * GET-only retry: fetchWithRetry refuses non-idempotent methods, and every
 * paginating caller below only ever GETs. This absorbs a transient
 * timeout/5xx on a single page without the caller's whole `step.run` — often
 * many pages deep — being replayed from page 1 by Inngest's own retry.
 *
 * The webhook subscribe/unsubscribe calls are POSTs and deliberately get a
 * single unretried attempt: a retried subscribe is a duplicate subscription,
 * i.e. duplicate deliveries on the PM's own account.
 */
async function lodgifyRawFetch(
  path:   string,
  apiKey: string,
  method: 'GET' | 'POST' | 'PUT' | 'DELETE',
  body:   unknown,
): Promise<Response> {
  try {
    if (method === 'GET') {
      return await fetchWithRetry(
        `${LODGIFY_API_BASE}${path}`,
        { method: 'GET', headers: lodgifyProvider.getApiHeaders(apiKey) },
        { timeoutMs: PMS_API_TIMEOUT_MS, label: `Lodgify ${path}`, attempts: 3 },
      )
    }

    return await fetch(`${LODGIFY_API_BASE}${path}`, {
      method,
      headers: lodgifyProvider.getApiHeaders(apiKey),
      body:    body === undefined ? undefined : JSON.stringify(body),
      signal:  AbortSignal.timeout(PMS_API_TIMEOUT_MS),
    })
  } catch (err) {
    // A timeout or transport failure that survived fetchWithRetry's own
    // attempts (or a POST's single unretried attempt) is exactly what the
    // breaker counts.
    await recordFailure('lodgify')
    throw err
  }
}

/**
 * One authenticated Lodgify request, returning the parsed JSON body.
 *
 * @throws RetryAfterError (via rateLimitRetry) when Lodgify throttles, so
 *         Inngest waits the interval Lodgify actually asked for instead of
 *         its own generic backoff curve. A bare RateLimitError escaping here
 *         is how hospitable-incremental-sync dead-lettered as "exhausted all
 *         retries: Rate limited — retry after 2s".
 * @throws NonRetriableError (with a typed `cause`) for a terminal status.
 */
export async function lodgifyFetch<T>(
  path:   string,
  apiKey: string,
  /** The connection this call is spent against — Lodgify quotas are per-key. */
  userId: string,
  init?:  LodgifyRequestInit,
): Promise<T> {
  await enforceLodgifyRateLimit(userId)

  // Circuit breaker, checked BEFORE the fetch — same chokepoint pattern as
  // hostexFetch and krogerFetch. Without it, every independent Lodgify sync
  // (initial, reconcile, webhook — across every connected org) keeps calling
  // through a provider-wide outage, each waiting out the full
  // PMS_API_TIMEOUT_MS and getting retried by Inngest's backoff, at the exact
  // moment the provider can least take the load.
  const { decision, priorFailures } = await evaluateBreaker('lodgify')
  if (decision === 'open') {
    throw new NonRetriableError(new CircuitOpenError('lodgify').message)
  }

  const res = await lodgifyRawFetch(path, apiKey, init?.method ?? 'GET', init?.body)

  if (!res.ok) await throwForStatus(res, path, init?.entityId)

  // A 204 (documented for unsubscribe) has no body to parse.
  if (res.status === 204) {
    if (priorFailures > 0) await recordSuccess('lodgify')
    return undefined as T
  }

  let parsed: T
  try {
    parsed = await res.json() as T
  } catch {
    // A 2xx whose body is not JSON is an edge/proxy page standing in for
    // Lodgify, not Lodgify answering — the breaker should count it.
    await recordFailure('lodgify')
    throw new Error(`Lodgify ${path} returned a non-JSON body: HTTP ${res.status}`)
  }

  // Only clear when there is something to clear — same as hostexFetch.
  if (priorFailures > 0) await recordSuccess('lodgify')

  return parsed
}

/**
 * Pull the row array out of a list response.
 *
 * Lodgify v2 is documented as `{ count, items }`, and some endpoints are
 * reported to answer with a bare array. Both are accepted.
 *
 * ANYTHING ELSE THROWS, and this is the single most important defensive
 * decision in this file. Returning [] for an unrecognised shape would make a
 * misparsed response indistinguishable from a genuinely empty account: the
 * initial sync would report "0 properties, synced successfully", and any
 * reconcile-by-absence pass reading that [] would treat every existing row as
 * deleted. The keys actually present are reported (never the values — a
 * booking body carries guest PII) so the fix is one Sentry issue away rather
 * than a debugging session.
 */
export function lodgifyExtractItems<T>(body: unknown, label: string): T[] {
  if (Array.isArray(body)) return body as T[]

  if (body && typeof body === 'object') {
    const items = (body as { items?: unknown }).items
    if (Array.isArray(items)) return items as T[]
  }

  const keys = body && typeof body === 'object' ? Object.keys(body as object).join(', ') : typeof body
  const err  = new Error(`Lodgify ${label} returned an unrecognized list shape. Keys present: ${keys}`)
  reportError(err, { site: 'lib.integrations.lodgify-api.lodgifyExtractItems' })
  throw err
}

/**
 * Walk a page/size collection to completion.
 *
 * Terminates on a short page rather than on `count`, so a `count` that is
 * stale, absent or wrong cannot cause either an early stop (silent data loss,
 * the failure mode this codebase keeps finding) or an endless loop.
 *
 * A numeric pagination loop — structurally exempt from
 * unit/guardrails/n-plus-one-loops.test.ts, and it issues one request per 50
 * rows rather than one per row.
 */
async function fetchAllPages<TRow>(
  buildPath: (page: number, size: number) => string,
  apiKey:    string,
  userId:    string,
  label:     string,
): Promise<TRow[]> {
  const rows: TRow[] = []

  // Lodgify's `page` is 1-based in its own examples.
  for (let page = 1; page <= MAX_PAGES; page++) {
    const body  = await lodgifyFetch<unknown>(buildPath(page, PAGE_SIZE), apiKey, userId)
    const batch = lodgifyExtractItems<TRow>(body, label)

    rows.push(...batch)
    if (batch.length < PAGE_SIZE) return rows
  }

  // Loud rather than silently truncated: returning what we have would look
  // exactly like a completed sync of a smaller portfolio.
  throw new Error(`Lodgify ${label} exceeded ${MAX_PAGES} pages (${rows.length} rows) — refusing to return a partial set`)
}

/** Every property on the connected Lodgify account. */
export async function lodgifyFetchProperties(apiKey: string, userId: string): Promise<LodgifyProperty[]> {
  return fetchAllPages<LodgifyProperty>(
    (page, size) => `/properties?page=${page}&size=${size}&includeCount=true`,
    apiKey,
    userId,
    'properties',
  )
}

export interface LodgifyBookingWindow {
  /** Inclusive YYYY-MM-DD lower bound on the stay window. */
  startDate: string
  /** Inclusive YYYY-MM-DD upper bound on the stay window. */
  endDate:   string
}

/**
 * A UTC date window, `historyMonths` back and `lookaheadMonths` forward.
 *
 * Exported for the same reason hostexReservationWindow is: the callers that
 * need it are Inngest functions whose steps must be deterministic, and the
 * window has to be computed in one place so the initial sync and the reconcile
 * cannot drift into covering different bands.
 */
export function lodgifyBookingWindow(historyMonths: number, lookaheadMonths: number): LodgifyBookingWindow {
  const start = new Date()
  start.setUTCMonth(start.getUTCMonth() - historyMonths)

  const end = new Date()
  end.setUTCMonth(end.getUTCMonth() + lookaheadMonths)

  return {
    startDate: start.toISOString().slice(0, 10),
    endDate:   end.toISOString().slice(0, 10),
  }
}

/**
 * Bookings whose stay overlaps the window.
 *
 * `stayFilter=ArrivalDate` with an explicit period is what Lodgify documents
 * for a date-bounded read. The bounds are ALWAYS sent: an unparameterised call
 * returns whatever default slice Lodgify chooses, which on an initial sync
 * looks like a PM with no history rather than like a truncated fetch.
 *
 * `includeTransactions` and the other expansion flags are deliberately not
 * requested — nothing here reads them, and a bigger payload is a bigger
 * surface for the shape guesses in lodgify.types.ts to be wrong about.
 */
export async function lodgifyFetchBookings(
  apiKey: string,
  userId: string,
  window: LodgifyBookingWindow,
): Promise<LodgifyBooking[]> {
  const qs = new URLSearchParams({
    stayFilter:    'DateRange',
    stayFilterDateFrom: window.startDate,
    stayFilterDateTo:   window.endDate,
    includeCount:  'true',
  })

  return fetchAllPages<LodgifyBooking>(
    (page, size) => `/reservations/bookings?${qs.toString()}&page=${page}&size=${size}`,
    apiKey,
    userId,
    `bookings[${window.startDate}..${window.endDate}]`,
  )
}

/**
 * One booking by id.
 *
 * What a webhook delivery needs. Returns null when the id matches nothing — a
 * booking hard-deleted between the delivery and this read is a legitimate
 * outcome, not an error to retry, and ProviderEntityGoneError is exactly that
 * signal rather than a fault.
 */
export async function lodgifyFetchBookingById(
  apiKey:    string,
  userId:    string,
  bookingId: string,
): Promise<LodgifyBooking | null> {
  try {
    const body = await lodgifyFetch<LodgifyBooking>(
      `/reservations/bookings/${encodeURIComponent(bookingId)}`,
      apiKey,
      userId,
      { entityId: bookingId },
    )
    return body?.id === undefined ? null : body
  } catch (err) {
    const inner = (err as { cause?: unknown })?.cause
    if (inner instanceof ProviderEntityGoneError) return null
    throw err
  }
}

// ── Webhooks ────────────────────────────────────────────────────────────────
//
// Lodgify's documented surface is subscribe / list / unsubscribe, keyed by
// (event, target_url). Every call below is reachable ONLY through
// lodgify-webhook.ts, which is itself gated on LODGIFY_WEBHOOKS_ENABLED — see
// that module for why registration is off by default.

/** Every webhook subscription Lodgify currently holds for this account. */
export async function lodgifyListWebhooks(apiKey: string, userId: string): Promise<LodgifyWebhookSubscription[]> {
  const body = await lodgifyFetch<unknown>('/webhooks/list', apiKey, userId)
  return lodgifyExtractItems<LodgifyWebhookSubscription>(body, 'webhooks/list')
}

/**
 * Subscribe one event to one URL, unless that exact pair is already
 * registered.
 *
 * Idempotent by check-then-create rather than by an upsert Lodgify does not
 * offer. The race that shape implies — two syncs subscribing at once — costs a
 * duplicate subscription, i.e. a duplicate delivery, which the handler already
 * absorbs (bookings upsert on (org_id, external_id, external_source) and
 * revenue dedups on source_reference_id). A lock would be more machinery than
 * the failure it prevents.
 */
export async function lodgifyEnsureWebhook(
  apiKey:    string,
  userId:    string,
  event:     LodgifyBookingEvent,
  targetUrl: string,
): Promise<{ created: boolean }> {
  const existing = await lodgifyListWebhooks(apiKey, userId)

  const alreadyRegistered = existing.some(
    (hook) => hook.event === event && hook.target_url === targetUrl,
  )

  if (alreadyRegistered) return { created: false }

  await lodgifyFetch('/webhooks/subscribe', apiKey, userId, {
    method: 'POST',
    body:   { event, target_url: targetUrl },
  })

  return { created: true }
}

/**
 * Remove every subscription pointing at one of our URLs.
 *
 * Matched on target_url rather than on a stored subscription id: the id is
 * Lodgify's and we never persisted one, while the URL is ours and carries the
 * per-connection token. Anything pointing at that token is by definition this
 * connection's.
 */
export async function lodgifyDeleteWebhooks(
  apiKey:    string,
  userId:    string,
  targetUrl: string,
): Promise<{ deleted: number }> {
  const existing = await lodgifyListWebhooks(apiKey, userId)
  const ours     = existing.filter((hook) => hook.target_url === targetUrl && hook.id !== null && hook.id !== undefined)

  let deleted = 0

  for (const hook of ours) {
    // One request per subscription because Lodgify's unsubscribe takes a
    // single id. Bounded by the number of events we subscribe to (three), not
    // by tenant data — this is not the N+1 shape the guardrail hunts.
    await lodgifyFetch('/webhooks/unsubscribe', apiKey, userId, {
      method: 'POST',
      body:   { id: hook.id },
    })
    deleted++
  }

  return { deleted }
}
